var s1w1a = `<b>LUNEDÌ</b><br>
7:15 sveglia - rasatura - ginnastica mattutina: corretta esecuzione - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER): nessuna informazione - entrata MINISTERO DELLA VERITÀ: scambio saluti con #67223 (ANDERSON THOMAS), #92873 (FOX ANNIE) - 8:30 posizionamento postazione di impiego - inizio mansione: revisione pellicola E743 - termine mansione: revisione pellicola E743  <br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #92873(FOX ANNIE), #88342 (BROWN RONALD): nessuna informazione - fine pausa pranzo - inizio mansione: scrittura pellicola F023 - termine mansione: scrittura pellicola F023 - uscita MINISTERO DELLA VERITÀ<br><br>

19:12 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111 - incontro con soggetto #73921 (ORNSTEIN EMMA): nessuna informazione  - 21:23 ritiro nei propri alloggi - visione trasmissione teleschermo: discorso grande fratello C021, notiziario K222 - pulizia serale - 22:40 riposo notturno<br><br>

<b>GIOVEDÌ</b><br>
7:15 sveglia - niente rasatura - ginnastica mattutina: corretta esecuzione - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER): nessuna informazione - entrata MINISTERO DELLA VERITÀ: scambio saluti con #92873(FOX ANNIE) - 8:30 posizionamento postazione di impiego - inizio mansione: preparazione materiale audiovisivo destinato ai prolet - termine mansione: preparazione materiale audiovisivo destinato ai prolet - 9:32 partenza da MINISTERO DELLA VERITÀ - 10:09 entrata BAR DELL’OLMO: fine area di azione di video/audio sorveglianza - 11:06 uscita BAR DELL’OLMO: inizio area di azione di video/audio sorveglianza - 11:43 entrata MINISTERO DELLA VERITÀ - posizionamento postazione di impiego: deposito materiale ottenuto <br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #92873(FOX ANNIE) - fine pausa pranzo - inizio mansione: registrazione indice di gradimento prolet - termine mansione: registrazione indice di gradimento prolet - inizio mansione: scrittura pellicola F024 - termine mansione: scrittura pellicola F024 - uscita MINISTERO DELLA VERITÀ<br><br>

19:28 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER): nessuna informazione - arrivo al tavolo soggetto #73921 (ORNSTEIN EMMA): subentro nel colloquio: nessuna informazione  - 21:42 ritiro nei propri alloggi - visione trasmissione teleschermo: notiziario K225 - pulizia serale - 22:35 riposo notturno`