var s1w1a3 = `<b>LUNEDÌ</b><br>
7:15 sveglia - rasatura: usura rasoio 70% - ginnastica mattutina: corretta esecuzione - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER): toni amichevoli: estratto conversazione [...dovresti provare...fammi sapere...] - tragitto in compagnia di soggetto #87013 (MINSON PETER): estratto conversazione [...sono a corto di lamette...] - entrata MINISTERO DELLA VERITÀ: scambio saluti con #67223 (ANDERSON THOMAS): saluto rispettoso, #92873(FOX ANNIE): saluto amichevole - 8:30 posizionamento postazione di impiego - inizio mansione: revisione pellicola E743 - termine mansione: revisione pellicola E743  <br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #92873(FOX ANNIE), #88342 (BROWN RONALD): toni amichevoli - fine pausa pranzo - inizio mansione: scrittura pellicola F023 - 15:50 pausa per servizi igenici - termine mansione: scrittura pellicola F023 - uscita MINISTERO DELLA VERITÀ - tragitto in solitudine<br><br>

19:12 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111 - incontro con soggetto #73921 (ORNSTEIN EMMA): toni di ringraziamento: ringraziamenti dovuti ai complimenti ricevuti per la diligenza nella ginnastica mattutina - 21:23 ritiro nei propri alloggi - visione trasmissione teleschermo: discorso grande fratello C021, notiziario K222 - pulizia serale - 22:40 riposo notturno<br><br>


<b>GIOVEDÌ</b><br>
7:15 sveglia - niente rasatura - ginnastica mattutina: corretta esecuzione - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER): toni di rimprovero: estratto coversazione [...ma non hai ancora seguito il mio consiglio!?...] - tragitto in solitudine - entrata MINISTERO DELLA VERITÀ: scambio saluti con #92873(FOX ANNIE): toni amichevoli - 8:30 posizionamento postazione di impiego - inizio mansione: preparazione materiale audiovisivo destinato ai prolet: pellicola E780, 3 fogli per annotazioni - termine mansione: preparazione materiale audiovisivo destinato ai prolet: pellicola E780, 3 fogli per annotazioni - 9:32 partenza da MINISTERO DELLA VERITÀ - tragitto in solitudine: scambio di saluti con 2 prolet - 10:09 entrata BAR DELL’OLMO: fine area di azione di video/audio sorveglianza - 11:06 uscita BAR DELL’OLMO: inizio area di azione di video/audio sorveglianza - tragitto in solitudine - 11:43 entrata MINISTERO DELLA VERITÀ - posizionamento postazione di impiego: deposito materiale ottenuto: pellicola E743, 3 fogli per annotazioni<br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #92873(FOX ANNIE): toni amichevoli - fine pausa pranzo - inizio mansione: registrazione indice di gradimento prolet - termine mansione: registrazione indice di gradimento prolet - inizio mansione: scrittura pellicola F024 - termine mansione: scrittura pellicola F024 - uscita MINISTERO DELLA VERITÀ - tragitto in solitudine: deviazione dal percorso abituale: acquisti al Mercato Nero: 3 lamette<br><br>

19:28 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER): toni neutri: estratto conversazione [...allora funziona...] - arrivo al tavolo soggetto #73921 (ORNSTEIN EMMA): subentro nel colloquio: toni amichevoli: estratto conversazione [...suo figlio è proprio un eroe...] - colloquio in corridoio con soggetto  #87013 (MINSON PETER): conversazione riguardo problemi idraulici: [...allora settimana prossima arrivo a contollare il lavandino...] - 21:42 ritiro nei propri alloggi - visione trasmissione teleschermo: notiziario K225 - pulizia serale - 22:35 riposo notturno `