var s1w2a1 = `<b>MARTEDÌ</b><br>
7:15 sveglia - rasatura - ginnastica mattutina: corretta esecuzione - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER): nessuna informazione - entrata MINISTERO DELLA VERITÀ: scambio saluti con #88342 (BROWN RONALD), #92873 (FOX ANNIE) - 8:30 posizionamento postazione di impiego - inizio mansione: preparazione materiale audiovisivo destinato ai prolet - termine mansione: preparazione materiale audiovisivo destinato ai prolet - 9:28 partenza da MINISTERO DELLA VERITÀ - 10:06 entrata BAR DELL’OLMO: fine area di azione di video/audio sorveglianza - 11:08 uscita BAR DELL’OLMO: inizio area di azione di video/audio sorveglianza - 11:44 entrata MINISTERO DELLA VERITÀ - posizionamento postazione di impiego: deposito materiale ottenuto <br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #92873 (FOX ANNIE) - fine pausa pranzo - inizio mansione: registrazione indice di gradimento prolet - termine mansione: registrazione indice di gradimento prolet - inizio mansione: scrittura pellicola F024 - termine mansione: scrittura pellicola F024 - uscita MINISTERO DELLA VERITÀ<br><br>

19:12 entrata CONDOMINIO VITTORIA 111 - pasto serale: mensa CONDOMINIO VITTORIA 111 - incontro con soggetto #73921 (ORNSTEIN EMMA), soggetto #87013 (MINSON PETER): nessuna informazione - congedo dal colloquio insieme al soggetto  #87013 (MINSON PETER) - accesso alloggio soggetto #87013 (MINSON PETER) in sua compagnia - aiuto per faccende domestiche soggetto #87013 (MINSON PETER) - 21:58 ritiro nei propri alloggi - visione trasmissione teleschermo: notiziario K230 - pulizia serale - 22:34 riposo notturno<br><br>

<b>DOMENICA</b><br>

8:00 sveglia - rasatura - ginnastica mattutina: corretta esecuzione - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER), soggetto #73921 (ORNSTEIN EMMA): nessuna informazione - inizio attività facoltativa: discorso partito interno Hyde Park - 9:15 partenza da CONDOMINIO VITTORIA 111 con gruppo di soggetto #73921 (ORNSTEIN EMMA) - 10:02 arrivo ad Hyde Park - termine attività facoltativa: discorso partito interno Hyde Park<br><br>

12:05 entrata CONDOMINIO VITTORIA 111 - pausa pranzo mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER): nessuna informazione - 15:34 accesso alloggio soggetto #87013 (MINSON PETER) in sua compagnia - aiuto per faccende domestiche soggetto #87013 (MINSON PETER) - arrivo soggetto #73921 (ORNSTEIN EMMA): bussa alla porta e offre aiuto - aiuto respinto - 16:30 uscita  CONDOMINIO VITTORIA 111 - camminata ricreativa - entrata CONDOMINIO VITTORIA 111<br><br>

19:06 pasto serale mensa CONDOMINIO VITTORIA 111 - coloquio con #86502 (HANCOCK ALEX): nessuna informazione - 21:23 ritiro nei propri alloggi - visione trasmissione teleschermo: discorso grande fratello C112, notiziario K235 - pulizia serale - 22:40 riposo notturno 
`;

var s1w2a1x = `<b>MARTEDÌ</b><br>
7:15 sveglia - rasatura - ginnastica mattutina: corretta esecuzione - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER): nessuna informazione - entrata MINISTERO DELLA VERITÀ: scambio saluti con #88342 (BROWN RONALD), #92873 (FOX ANNIE) - 8:30 posizionamento postazione di impiego - inizio mansione: preparazione materiale audiovisivo destinato ai prolet - termine mansione: preparazione materiale audiovisivo destinato ai prolet - 9:28 partenza da MINISTERO DELLA VERITÀ - 10:06 entrata BAR DELL’OLMO: fine area di azione di video/audio sorveglianza - 10:32 uscita BAR DELL’OLMO: inizio area di azione di video/audio sorveglianza - 11:10 entrata MINISTERO DELLA VERITÀ - posizionamento postazione di impiego: deposito materiale ottenuto <br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #92873 (FOX ANNIE) - fine pausa pranzo - inizio mansione: registrazione indice di gradimento prolet - termine mansione: registrazione indice di gradimento prolet - inizio mansione: scrittura pellicola F024 - termine mansione: scrittura pellicola F024 - uscita MINISTERO DELLA VERITÀ<br><br>


19:12 entrata CONDOMINIO VITTORIA 111 - pasto serale: mensa CONDOMINIO VITTORIA 111 - incontro con soggetto #73921 (ORNSTEIN EMMA), soggetto #87013 (MINSON PETER): nessuna informazione - congedo dal colloquio insieme al soggetto  #87013 (MINSON PETER) - accesso alloggio soggetto #87013 (MINSON PETER) in sua compagnia - aiuto per faccende domestiche soggetto #87013 (MINSON PETER) - 21:58 ritiro nei propri alloggi - visione trasmissione teleschermo: notiziario K230 - pulizia serale - 22:34 riposo notturno<br><br>

DOMENICA<br>

8:00 sveglia - rasatura - ginnastica mattutina: corretta esecuzione - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER), soggetto #73921 (ORNSTEIN EMMA): nessuna informazione - inizio attività facoltativa: discorso partito interno Hyde Park - 9:15 partenza da CONDOMINIO VITTORIA 111 con gruppo di soggetto #73921 (ORNSTEIN EMMA) - 10:02 arrivo ad Hyde Park - termine attività facoltativa: discorso partito interno Hyde Park<br><br>

12:05 entrata CONDOMINIO VITTORIA 111 - pausa pranzo mensa CONDOMINIO VITTORIA 111: colloquio sbrigativo con soggetto #87013 (MINSON PETER): nessuna informazione - ritiro nei propri alloggi - visione trasmissione teleschermo: discorso Grande Fratello C112 -  colloquio in corridoio con soggetto #73921 (ORNSTEIN EMMA): nessuna  informazione - 16:30 uscita  CONDOMINIO VITTORIA 111 - camminata ricreativa - entrata CONDOMINIO VITTORIA 111<br><br>

19:06 pasto serale mensa CONDOMINIO VITTORIA 111 - coloquio con #86502 (HANCOCK ALEX): nessuna informazione - 21:23 ritiro nei propri alloggi - visione trasmissione teleschermo: discorso grande fratello C112, notiziario K235 - pulizia serale - 22:40 riposo notturno
`;

var s1w2a2 = `<b>MARTEDÌ</b><br>
7:15 sveglia - rasatura - ginnastica mattutina: corretta esecuzione - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER): toni neutri - tragitto in compagni di soggetto #87013 (MINSON PETER): toni rassicuranti - entrata MINISTERO DELLA VERITÀ: scambio saluti con #88342 (BROWN RONALD), #92873 (FOX ANNIE) - 8:30 posizionamento postazione di impiego - inizio mansione: preparazione materiale audiovisivo destinato ai prolet: pellicola E993, 3 fogli per annotazioni - termine mansione: preparazione materiale audiovisivo destinato ai prolet:  pellicola E993, 3 fogli per annotazioni - 9:28 partenza da MINISTERO DELLA VERITÀ - tragitto in solitudine - 10:06 entrata BAR DELL’OLMO: fine area di azione di video/audio sorveglianza - 11:08 uscita BAR DELL’OLMO: inizio area di azione di video/audio sorveglianza - 11:44 entrata MINISTERO DELLA VERITÀ - posizionamento postazione di impiego: deposito materiale ottenuto: pellicola E780 - 3 fogli per annotazioni <br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #92873 (FOX ANNIE): toni amichevoli - fine pausa pranzo -inizio mansione: registrazione indice di gradimento prolet - termine mansione: registrazione indice di gradimento prolet - inizio mansione: scrittura pellicola F024 - termine mansione: scrittura pellicola F024 - uscita MINISTERO DELLA VERITÀ<br><br>

19:12 entrata CONDOMINIO VITTORIA 111 - pasto serale: mensa CONDOMINIO VITTORIA 111 - incontro con soggetto #73921 (ORNSTEIN EMMA), soggetto #87013 (MINSON PETER): toni amichevoli - congedo dal colloquio insieme al soggetto  #87013 (MINSON PETER) - accesso alloggio soggetto #87013 (MINSON PETER) in sua compagnia - aiuto per faccende domestiche soggetto #87013 (MINSON PETER): manutenzione lavandino - 21:58 ritiro nei propri alloggi - visione trasmissione teleschermo: notiziario K230 - pulizia serale - 22:34 riposo notturno<br><br>

<b>DOMENICA</b><br>

8:00 sveglia - rasatura - ginnastica mattutina: corretta esecuzione - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER), soggetto #73921 (ORNSTEIN EMMA): toni amichevoli - segue pacca sulla spalla al #87013 (MINSON PETER) - inizio attività facoltativa: discorso partito interno Hyde Park - 9:15 partenza da CONDOMINIO VITTORIA 111 con gruppo di soggetto #73921 (ORNSTEIN EMMA) - 10:02 arrivo ad Hyde Park - ascolto interessato del discorso - termine attività facoltativa: discorso partito interno Hyde Park<br><br>

12:05 entrata CONDOMINIO VITTORIA 111 - pausa pranzo mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER): offerta di aiuto - 15:34 accesso alloggio soggetto #87013 (MINSON PETER) in sua compagnia - aiuto per faccende domestiche soggetto #87013 (MINSON PETER): manutenzione lavandino - arrivo soggetto #73921 (ORNSTEIN EMMA): bussa alla porta e offre aiuto - aiuto respinto: toni amichevoli - 16:30 uscita  CONDOMINIO VITTORIA 111 - camminata ricreativa - tragitto in solitudine -entrata CONDOMINIO VITTORIA 111<br><br>

19:06 pasto serale mensa CONDOMINIO VITTORIA 111 - coloquio con #86502 (HANCOCK ALEX): toni amichevoli - 21:23 ritiro nei propri alloggi - visione trasmissione teleschermo: discorso grande fratello C112, notiziario K235 - pulizia serale - 22:40 riposo notturno
`;

var s1w2a2x = `<b>MARTEDÌ</b><br>
7:15 sveglia - rasatura - ginnastica mattutina: corretta esecuzione - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER): toni neutri - tragitto in solitudine - entrata MINISTERO DELLA VERITÀ: scambio saluti con #88342 (BROWN RONALD), #92873 (FOX ANNIE) - 8:30 posizionamento postazione di impiego - inizio mansione: preparazione materiale audiovisivo destinato ai prolet: pellicola E993, 3 fogli per annotazioni- termine mansione: preparazione materiale audiovisivo destinato ai prolet:  pellicola E993, 3 fogli per annotazioni - 9:28 partenza da MINISTERO DELLA VERITÀ - tragitto in solitudine - 10:06 entrata BAR DELL’OLMO: fine area di azione di video/audio sorveglianza - 10:32 uscita BAR DELL’OLMO: inizio area di azione di video/audio sorveglianza - 11:10 entrata MINISTERO DELLA VERITÀ - posizionamento postazione di impiego: deposito materiale ottenuto: pellicola E780 - 3 fogli per annotazioni <br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #92873 (FOX ANNIE): toni amichevoli - fine pausa pranzo - inizio mansione: registrazione indice di gradimento prolet - termine mansione: registrazione indice di gradimento prolet - inizio mansione: scrittura pellicola F024 - termine mansione: scrittura pellicola F024 - uscita MINISTERO DELLA VERITÀ<br><br>

19:12 entrata CONDOMINIO VITTORIA 111 - pasto serale: mensa CONDOMINIO VITTORIA 111 - incontro con soggetto #73921 (ORNSTEIN EMMA), soggetto #87013 (MINSON PETER): toni amichevoli - congedo dal colloquio insieme al soggetto  #87013 (MINSON PETER) - accesso alloggio soggetto #87013 (MINSON PETER) in sua compagnia - aiuto per faccende domestiche soggetto #87013 (MINSON PETER): manutenzione lavandino - 21:58 ritiro nei propri alloggi - visione trasmissione teleschermo: notiziario K230 - pulizia serale - 22:34 riposo notturno<br><br>

<b>DOMENICA</b><br>

8:00 sveglia - rasatura - ginnastica mattutina: corretta esecuzione - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER), soggetto #73921 (ORNSTEIN EMMA): toni neutri - inizio attività facoltativa: discorso partito interno Hyde Park - 9:15 partenza da CONDOMINIO VITTORIA 111 con gruppo di soggetto #73921 (ORNSTEIN EMMA) - 10:02 arrivo ad Hyde Park - ascolto interessato del discorso - termine attività facoltativa: discorso partito interno Hyde Park <br><br>

12:05 entrata CONDOMINIO VITTORIA 111 - pausa pranzo mensa CONDOMINIO VITTORIA 111: colloquio sbrigativo con soggetto #87013 (MINSON PETER): toni scocciati - ritiro nei propri alloggi - visione trasmissione teleschermo: discorso Grande Fratello C112 - colloquio in corridoio con soggetto #73921 (ORNSTEIN EMMA): toni amichevoli - 16:30 uscita  CONDOMINIO VITTORIA 11 - camminata ricreativa - entrata CONDOMINIO VITTORIA 111<br><br>

19:06 pasto serale mensa CONDOMINIO VITTORIA 111 - coloquio con #86502 (HANCOCK ALEX): toni amichevoli - 21:23 ritiro nei propri alloggi - visione trasmissione teleschermo: discorso grande fratello C112, notiziario K235 - pulizia serale - 22:40 riposo notturno
`;

var s1w2a3 = `<b>MARTEDÌ</b><br>
7:15 sveglia - rasatura: usura rasoio 15% - ginnastica mattutina: corretta esecuzione - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER): toni neutri: estratto conversazione [...stasera...] - tragitto in compagni di soggetto #87013 (MINSON PETER): toni rassicuranti [...non preoccuparti, ci penso io...] - entrata MINISTERO DELLA VERITÀ: scambio saluti con #88342 (BROWN RONALD), #92873 (FOX ANNIE): saluto amichevole - 8:30 posizionamento postazione di impiego - inizio mansione: preparazione materiale audiovisivo destinato ai prolet: pellicola E993, 3 fogli per annotazioni - termine mansione: preparazione materiale audiovisivo destinato ai prolet:  pellicola E993, 3 fogli per annotazioni - 9:28 partenza da MINISTERO DELLA VERITÀ - tragitto in solitudine: scambio di saluti con 2 prolet - 10:06 entrata BAR DELL’OLMO: fine area di azione di video/audio sorveglianza - 11:08 uscita BAR DELL’OLMO: inizio area di azione di video/audio sorveglianza - 11:44 entrata MINISTERO DELLA VERITÀ - posizionamento postazione di impiego: deposito materiale ottenuto: pellicola E780 - 3 fogli per annotazioni<br><br> 

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #92873 (FOX ANNIE): toni amichevoli - fine pausa pranzo - inizio mansione: registrazione indice di gradimento prolet - termine mansione: registrazione indice di gradimento prolet - inizio mansione: scrittura pellicola F024 - termine mansione: scrittura pellicola F024 - uscita MINISTERO DELLA VERITÀ - tragitto in solitudine<br><br>

19:12 entrata CONDOMINIO VITTORIA 111 - pasto serale: mensa CONDOMINIO VITTORIA 111 - incontro con soggetto #73921 (ORNSTEIN EMMA), soggetto #87013 (MINSON PETER): toni amichevoli: estratto conversazione [...devo aiutarlo ad aggiustare delle tubature...] - congedo dal colloquio insieme al soggetto  #87013 (MINSON PETER) - accesso alloggio soggetto #87013 (MINSON PETER) in sua compagnia - aiuto per faccende domestiche soggetto #87013 (MINSON PETER): manutenzione lavandino: estratto conversazione [...stai zitto...] - 21:58 ritiro nei propri alloggi - visione trasmissione teleschermo: notiziario K230 - pulizia serale - 22:34 riposo notturno<br><br>

<b>DOMENICA</b><br>

8:00 sveglia - rasatura - ginnastica mattutina: corretta esecuzione - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER), soggetto #73921 (ORNSTEIN EMMA): toni amichevoli: estratto conversazione [...dai Peter, vieni anche tu...] - segue pacca sulla spalla al #87013 (MINSON PETER) - inizio attività facoltativa: discorso partito interno Hyde Park - 9:15 partenza da CONDOMINIO VITTORIA 111 con gruppo di soggetto #73921 (ORNSTEIN EMMA) - 10:02 arrivo ad Hyde Park - ascolto interessato del discorso - termine attività facoltativa: discorso partito interno Hyde Park<br><br>

12:05 entrata CONDOMINIO VITTORIA 111 - pausa pranzo mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER): offerta di aiuto: estratto conversazione [...dopo vediamo di risolvere la questione del lavandino...] - 15:34 accesso alloggio soggetto #87013 (MINSON PETER) in sua compagnia - aiuto per faccende domestiche soggetto #87013 (MINSON PETER): manutenzione lavandino - soggetto #73921 (ORNSTEIN EMMA): bussa alla porta e offre aiuto - aiuto respinto: toni amichevoli: estratto conversazione [...grazie Emma, ma abbiamo quasi risolto...] - 16:30 uscita CONDOMINIO VITTORIA 111 - camminata ricreativa - tragitto in solitudine - consumo sigarette: quantità: 1 - entrata CONDOMINIO VITTORIA 111<br><br>

19:06 pasto serale mensa CONDOMINIO VITTORIA 111 - coloquio con #86502 (HANCOCK ALEX): toni amichevoli - 21:23 ritiro nei propri alloggi - visione trasmissione teleschermo: discorso grande fratello C112, notiziario K235 - pulizia serale - 22:40 riposo notturno
`;

var s1w2a3x = `<b>MARTEDÌ</b><br>
7:15 sveglia - rasatura: usura rasoio 15% - ginnastica mattutina: corretta esecuzione - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER): toni neutri: estratto conversazione [...stasera...] - tragitto in solitudine - entrata MINISTERO DELLA VERITÀ: scambio saluti con #88342 (BROWN RONALD): saluto amichevole, #92873 (FOX ANNIE) - 8:30 posizionamento postazione di impiego - inizio mansione: preparazione materiale audiovisivo destinato ai prolet: pellicola E993, 3 fogli per annotazioni - termine mansione: preparazione materiale audiovisivo destinato ai prolet:  pellicola E993, 3 fogli per annotazioni - 9:28 partenza da MINISTERO DELLA VERITÀ - tragitto in solitudine: scambio di saluti con 2 prolet - 10:06 entrata BAR DELL’OLMO: fine area di azione di video/audio sorveglianza - 10:32 uscita BAR DELL’OLMO: inizio area di azione di video/audio sorveglianza - 11:10 entrata MINISTERO DELLA VERITÀ - posizionamento postazione di impiego: deposito materiale ottenuto: pellicola E780 - 3 fogli per annotazioni <br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #92873 (FOX ANNIE): toni amichevoli - fine pausa pranzo - inizio mansione: registrazione indice di gradimento prolet - termine mansione: registrazione indice di gradimento prolet - inizio mansione: scrittura pellicola F024 - termine mansione: scrittura pellicola F024 - uscita MINISTERO DELLA VERITÀ - tragitto in solitudine<br><br>

19:12 entrata CONDOMINIO VITTORIA 111 - pasto serale: mensa CONDOMINIO VITTORIA 111 - incontro con soggetto #73921 (ORNSTEIN EMMA), soggetto #87013 (MINSON PETER): toni amichevoli: estratto conversazione [... devo aiutarlo ad aggiustare delle tubature...] - congedo dal colloquio insieme al soggetto  #87013 (MINSON PETER) - accesso alloggio soggetto #87013 (MINSON PETER) in sua compagnia - aiuto per faccende domestiche soggetto #87013 (MINSON PETER): manutenzione lavandino: estratto conversazione [... fai silenzio...] - 21:58 ritiro nei propri alloggi - visione trasmissione teleschermo: notiziario K230 - pulizia serale - 22:34 riposo notturno<br><br>

DOMENICA<br>

8:00 sveglia - rasatura - ginnastica mattutina: corretta esecuzione - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER), soggetto #73921 (ORNSTEIN EMMA): toni neutri: estratto conversazione [...Peter, quindi vieni anche tu?...] - inizio attività facoltativa: discorso partito interno Hyde Park - 9:15 partenza da CONDOMINIO VITTORIA 111 con gruppo di soggetto #73921 (ORNSTEIN EMMA) - 10:02 arrivo ad Hyde Park - ascolto interessato del discorso - termine attività facoltativa: discorso partito interno Hyde Park<br><br>

12:05 entrata CONDOMINIO VITTORIA 111 - pausa pranzo mensa CONDOMINIO VITTORIA 111: colloquio sbrigativo con soggetto #87013 (MINSON PETER): toni scocciati: estratto conversazione [...non oggi Peter...meglio aspettare...] - ritiro nei propri alloggi - visione trasmissione teleschermo: discorso Grande Fratello C112 - colloquio in corridoio con soggetto #73921 (ORNSTEIN EMMA): toni amichevoli: [...non potevo aiutarlo, dovevo assolutamente sentire il discorso del Grande Fratello...] - 16:30 uscita  CONDOMINIO VITTORIA 11 - camminata ricreativa - tragitto in solitudine - consumo sigarette: quantità: 1 - entrata CONDOMINIO VITTORIA 111<br><br>

19:06 pasto serale mensa CONDOMINIO VITTORIA 111 - coloquio con #86502 (HANCOCK ALEX): toni amichevoli - 21:23 ritiro nei propri alloggi - visione trasmissione teleschermo: discorso grande fratello C112, notiziario K235 - pulizia serale - 22:40 riposo notturno
`;

var s1b2 = `Il soggetto #80085 (DICK ANDREW) sembra particolarmente devoto al suo lavoro: per quanto sia umiliante approfondisce il suo discorso con il barista più dello stretto necessario. Riempe diligentemente i sui fogli con dei fitti appunti e sembra chiedere spesso conferma di quello che scrive, facendo leggere alcune note al gestore del locale, non limitandosi quindi solo ad un mero ascolto passivo degli interlocutori.<br><br>

Generalmente il soggetto sembra molto stimato dai prolet, probabilmente a causa della sua attitudine e della natura ricreativa dei prodotti che fornisce al Bar dell’Olmo.
`