var s1w2a3 = `<b>MARTEDÌ</b><br>
7:15 sveglia - rasatura: usura rasoio 15% - ginnastica mattutina: corretta esecuzione - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER): toni neutri: estratto conversazione [...stasera...] - tragitto in compagni di soggetto #87013 (MINSON PETER): toni rassicuranti [...non preoccuparti, ci penso io...] - entrata MINISTERO DELLA VERITÀ: scambio saluti con #88342 (BROWN RONALD), #92873 (FOX ANNIE): saluto amichevole - 8:30 posizionamento postazione di impiego - inizio mansione: preparazione materiale audiovisivo destinato ai prolet: pellicola E993, 3 fogli per annotazioni - termine mansione: preparazione materiale audiovisivo destinato ai prolet:  pellicola E993, 3 fogli per annotazioni - 9:28 partenza da MINISTERO DELLA VERITÀ - tragitto in solitudine: scambio di saluti con 2 prolet - 10:06 entrata BAR DELL’OLMO: fine area di azione di video/audio sorveglianza - 11:08 uscita BAR DELL’OLMO: inizio area di azione di video/audio sorveglianza - 11:44 entrata MINISTERO DELLA VERITÀ - posizionamento postazione di impiego: deposito materiale ottenuto: pellicola E780 - 3 fogli per annotazioni<br><br> 

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #92873 (FOX ANNIE): toni amichevoli - fine pausa pranzo - inizio mansione: registrazione indice di gradimento prolet - termine mansione: registrazione indice di gradimento prolet - inizio mansione: scrittura pellicola F024 - termine mansione: scrittura pellicola F024 - uscita MINISTERO DELLA VERITÀ - tragitto in solitudine<br><br>

19:12 entrata CONDOMINIO VITTORIA 111 - pasto serale: mensa CONDOMINIO VITTORIA 111 - incontro con soggetto #73921 (ORNSTEIN EMMA), soggetto #87013 (MINSON PETER): toni amichevoli: estratto conversazione [...devo aiutarlo ad aggiustare delle tubature...] - congedo dal colloquio insieme al soggetto  #87013 (MINSON PETER) - accesso alloggio soggetto #87013 (MINSON PETER) in sua compagnia - aiuto per faccende domestiche soggetto #87013 (MINSON PETER): manutenzione lavandino: estratto conversazione [...stai zitto...] - 21:58 ritiro nei propri alloggi - visione trasmissione teleschermo: notiziario K230 - pulizia serale - 22:34 riposo notturno<br><br>

<b>DOMENICA</b><br>

8:00 sveglia - rasatura - ginnastica mattutina: corretta esecuzione - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER), soggetto #73921 (ORNSTEIN EMMA): toni amichevoli: estratto conversazione [...dai Peter, vieni anche tu...] - segue pacca sulla spalla al #87013 (MINSON PETER) - inizio attività facoltativa: discorso partito interno Hyde Park - 9:15 partenza da CONDOMINIO VITTORIA 111 con gruppo di soggetto #73921 (ORNSTEIN EMMA) - 10:02 arrivo ad Hyde Park - ascolto interessato del discorso - termine attività facoltativa: discorso partito interno Hyde Park<br><br>

12:05 entrata CONDOMINIO VITTORIA 111 - pausa pranzo mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER): offerta di aiuto: estratto conversazione [...dopo vediamo di risolvere la questione del lavandino...] - 15:34 accesso alloggio soggetto #87013 (MINSON PETER) in sua compagnia - aiuto per faccende domestiche soggetto #87013 (MINSON PETER): manutenzione lavandino - soggetto #73921 (ORNSTEIN EMMA): bussa alla porta e offre aiuto - aiuto respinto: toni amichevoli: estratto conversazione [...grazie Emma, ma abbiamo quasi risolto...] - 16:30 uscita CONDOMINIO VITTORIA 111 - camminata ricreativa - tragitto in solitudine - consumo sigarette: quantità: 1 - entrata CONDOMINIO VITTORIA 111<br><br>

19:06 pasto serale mensa CONDOMINIO VITTORIA 111 - coloquio con #86502 (HANCOCK ALEX): toni amichevoli - 21:23 ritiro nei propri alloggi - visione trasmissione teleschermo: discorso grande fratello C112, notiziario K235 - pulizia serale - 22:40 riposo notturno`
