var s2w1a3 = `<b>LUNEDÌ</b><br>
7:15 sveglia - ginnastica mattutina: esercizio svolto in maniera approssimativa - richiamo da parte dell’istruttrice - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW): toni amichevoli: estratto conversazione [...proverò...ti faccio sapere appena lo faccio...] - incontro con soggetto #73921 (ORNSTEIN EMMA): giustificazione affrettata: scuse per richiamo mattutino - tragitto in compagnia di soggetto #80085 (DICK ANDREW): estratto conversazione [...penso passerò a prendere delle sigarette...] - entrata MINISTERO DELLA VERITÀ - posizionamento postazione di impiego - inizio mansione: correzione refusi quotidiano C243 - numero pagine per annotazioni fornite: 5 - termine mansione: correzione refusi quotidiano C243 - numero pagine eliminate registrate: 5<br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #91351 (HILL LEON): elogio notizie del giorno - fine pausa pranzo - inizio mansione: revisione discorso Grande Fratello H011 - numero pagine per annotazioni fornite: 3 - termine mansione: revisione discorso Grande Fratello H011 - numero pagine eliminate registrate: 3 - uscita MINISTERO DELLA VERITÀ - deviazione da tragitto abituale: acquisti a Mercato Nero: 20 sigarette<br><br>

19:15 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111 - 21:32 ritiro nei propri alloggi - pulizia serale - mansioni domestiche - 22:27 riposo notturno<br><br>

<b>GIOVEDÌ</b><br>
7:15 sveglia - ginnastica mattutina: esecuzione accettabile - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW): toni di scuse: estratto conversazione [...ci penso oggi...] - ritiro in camera - uscita da CONDOMINIO VITTORIA 111 - entrata MINISTERO DELLA VERITÀ: ritardo di 10 minuti - 8:40 posizionamento postazione di impiego - inizio mansione: revisione e correzione notizie quotidiano G563 - numero pagine per annotazioni fornite: 3 - termine mansione: revisione e correzione notizie quotidiano G563 - numero pagine eliminate registrate: 4 - estratto audio [...funziona!...]<br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #91351 (HILL LEON), #90672 (HOPPER DANA): toni affettuosi: conversazione appassionata sul Partito - fine pausa pranzo - inizio mansione: rettifica notizie di guerra malriportate - numero pagine per annotazioni fornite: 2 - termine mansione: rettifica notizie di guerra malriportate - numero pagine eliminate registrate: 3 - uscita MINISTERO DELLA VERITÀ - tragitto in solitudine<br><br>

19:10 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW): toni eccitati: estratto conversazione [...la tua idea ha funzionato...] - arrivo al tavolo soggetto #73921 (ORNSTEIN EMMA): subentro nel colloquio: toni neutri: estratto conversazione [...eh...la guerra...] - colloquio in corridoio con soggetto #80085 (DICK ANDREW): conversazione riguardo a problemi idraulici: estratto conversazione [...quindi settimana prossima arrivi a controllare il lavandino...] - 21:42 ritiro nei propri alloggi - manutenzione lavandino - pulizia serale - 22:46 riposo notturno


`
