var s2w2a3 = `<b>GIOVEDÌ</b><br>
7:15 sveglia - ginnastica mattutina: corretta esecuzione - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #73921 (ORNSTEIN EMMA): toni preoccupati: estratto conversazione [...mi sta aiutando ad aggiustare il gabinetto...] - tragitto in compagnia di soggetto #80085 (DICK ANDREW): estratto conversazione [...quella vecchia...insopportabile] - entrata MINISTERO DELLA VERITÀ: scambio di saluti con #90672 (HOPPER DANA): toni amichevoli - 8:30 posizionamento postazione di impiego - inizio mansione: correzione refusi notizie MINISTERO DELL’ABBONDANZA F782 - numero pagine per annotazioni fornite: 3 - termine mansione: correzione refusi notizie MINISTERO DELL’ABBONDANZA F782 - numero pagine eliminate registrate: 3<br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con soggetto #80085 (DICK ANDREW): conversazione riguardo al lavoro: estratto conversazione [...tutto bene come al solito...] - fine pausa pranzo - inizio mansione: revisione notizie di guerra malriportate - numero pagine per annotazioni fornite: 2 - termine mansione: revisione notizie di guerra malriportate - numero pagine eliminate registrate: 2 - uscita MINISTERO DELLA VERITÀ - ritorno in solitudine <br><br>

19:11 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW): toni amichevoli: estratto conversazione [...oggi meglio di no...] - 21:29 ritiro nei propri alloggi - consumo sigarette: quantità: 2 - colpi alla porta: interruzione attività da parte del soggetto #73921 (ORNSTEIN EMMA): scuse per il fetore: estratto conversazione [...ma è solo del tabacco...] - manutenzione lavandino - pulizia serale - 22:35 riposo notturno<br><br>


<b>DOMENICA</b><br>
8:00 sveglia - ginnastica mattutina: esecuzione tollerabile - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #73921 (ORNSTEIN EMMA): toni amichevoli: estratto conversazione [...va bene...vengo...] - inizio attività facoltativa: discorso partito interno Hyde Park - 9:15 partenza da CONDOMINIO VITTORIA 111 con gruppo di soggetto #73921 (ORNSTEIN EMMA) - 10:02 arrivo ad Hyde Park - ascolto intermittente del discorso - termine attività facoltativa: discorso partito interno Hyde Park<br><br>

12:05 entrata CONDOMINIO VITTORIA 111 - pausa pranzo mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW): richiesta di aiuto - estratto conversazione [...mi dai una mano anche oggi per il lavandino?...] - 15:34 accesso alloggio in compagnia del soggetto #80085 (DICK ANDREW) - faccende domestiche aiutato da soggetto #80085 (DICK ANDREW) - arrivo soggetto #73921 (ORNSTEIN EMMA): bussa alla porta e offre aiuto - aiuto respinto - toni irritati - estratto conversazione [...dai...non adesso...] - 17:03 uscita CONDOMINIO VITTORIA 111 - arrivo Mercato Nero: acquisti: 1 lametta - arrivo pattuglia psicopolizia - deviazione dal percorso - entrata CONDOMINIO VITTORIA 111<br><br>

19:20 pasto serale mensa CONDOMINIO VITTORIA 111 - coloquio con #86502 (HANCOCK ALEX): discussione riguardo a soggetto #73921 (ORNSTEIN EMMA) - estratto conversazione [...è davvero insopportabile...] - 21:36 ritiro nei propri alloggi - manutenzione lavandino - consumo sigarette: quantità: 3 - 22:23 riposo notturno

`
