var s2w3a3 = `<b>LUNEDÌ</b><br>
7:15 sveglia - rasatura: usura rasoio 10% - ginnastica mattutina: esercizio svolto in maniera approssimativa - richiamo da parte dell’istruttrice - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW): toni neutri: [...come sta andando?...non c’è altro che posso fare?...] - incontro in corridoio con soggetto #73921 (ORNSTEIN EMMA): sguardo indifferente - tragitto in compagnia di soggetto #80085 (DICK ANDREW) - entrata MINISTERO DELLA VERITÀ - 8:29 posizionamento postazione di impiego - inizio mansione: correzione refusi notizie di guerra - numero pagine per annotazioni fornite: 4 - RITARDO MACCHINARI DI CONSEGNA DOCUMENTI: non previsto - rilevata sudorazione: estratto audio [...ma ha sempre funzionato...] - termine mansione: correzione refusi notizie di guerra - numero pagine eliminate registrate: 4<br><br> 

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #90672 (HOPPER DANA): sguardi insistenti: commenti sull’abbigliamento di #90672 (HOPPER DANA) - fine pausa pranzo - inizio mansione: correzione notizie razionamento cioccolato C103 - numero pagine per annotazioni fornite: 3 - sguardo eccessivamente preoccupato - termine mansione: correzione notizie razionamento cioccolato C103 - numero pagine eliminate registrate: 3 - uscita MINISTERO DELLA VERITÀ<br><br>

19:18 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #73921 (ORNSTEIN EMMA): evidente preoccupazione: estratto conversazione [...non preoccuparti abbiamo già aggiustato il lavandino...] - incontro in corridoio con soggetto #80085 (DICK ANDREW): toni preoccupati: estratto conversazione [...adesso che si fa?...] - 21:33 ritiro nei propri alloggi - pulizia serale - mansioni domestiche - manutenzione lavandino - consumo sigarette: quantità: 1 - 22:37 riposo notturno<br><br>


<b>VENERDÌ</b><br>
7:15 sveglia - rasatura: usura rasoio 50% - ginnastica mattutina: esecuzione tollerabile - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #73921 (ORNSTEIN EMMA): conversazione sulla giornata di lavoro - tragitto in compagnia del soggetto #80085 (DICK ANDREW) - entrata MINISTERO DELLA VERITÀ - 8:30 posizionamento postazione di impiego - inizio mansione: correzione discorso Grande Fratello M383 - numero pagine per annotazioni fornite: 3 - rovista più volte nelle tasche - pausa per servizi igienici: incontro con soggetto #80085 (DICK ANDREW): saluto con stretta di mano - termine mansione: correzione discorso Grande Fratello M383 - numero pagine eliminate registrate: 3<br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #91351 (HILL LEON): conversazione riguardante gli interessi procreativi: estratto conversazione [...forse ho trovata quella giusta...] - fine pausa pranzo - inizio mansione: revisione rapporto su tenore di vita N193 - numero pagine per annotazioni fornite: 5 - termine mansione: revisione rapporto su tenore di vita N193 - numero pagine eliminate registrate: 5 - uscita MINISTERO DELLA VERITÀ - tragitto in solitudine - deviazione da percorso abituale: acquisti a Mercato Nero: 10 sigarette<br><br> 

19:17 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con #86502 (HANCOCK ALEX): toni amichevoli: estratto conversazione [...tra tutti i Condomini Vittoria doveva proprio capitarci lei come istruttrice?...] - 21:27 ritiro nei propri alloggi - manutenzione lavandino - consumo sigarette: quantità: 2 - 22:46 riposo notturno
`
