var s2w3a2 = `<b>LUNEDÌ</b><br>
7:15 sveglia - rasatura - ginnastica mattutina: esercizio svolto in maniera approssimativa - richiamo da parte dell’istruttrice - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW): toni neutri - incontro in corridoio con soggetto #73921 (ORNSTEIN EMMA): sguardo indifferente - tragitto in compagnia di soggetto #80085 (DICK ANDREW) - entrata MINISTERO DELLA VERITÀ - 8:29 posizionamento postazione di impiego - inizio mansione: correzione refusi notizie di guerra - numero pagine per annotazioni fornite: 4 - RITARDO MACCHINARI DI CONSEGNA DOCUMENTI: non previsto - termine mansione: correzione refusi notizie di guerra - numero pagine eliminate registrate: 4<br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #90672 (HOPPER DANA): sguardi insistenti - fine pausa pranzo - inizio mansione: correzione notizie razionamento cioccolato C103 - numero pagine per annotazioni fornite: 3 - termine mansione: correzione notizie razionamento cioccolato C103 - numero pagine eliminate registrate: 3 - uscita MINISTERO DELLA VERITÀ <br><br>

19:18 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #73921 (ORNSTEIN EMMA): evidente preoccupazione: estratto conversazione [...non preoccuparti abbiamo già aggiustato il lavandino...] - incontro in corridoio con soggetto #80085 (DICK ANDREW): toni preoccupati - 21:33 ritiro nei propri alloggi - pulizia serale - mansioni domestiche - manutenzione lavandino - consumo sigarette: quantità: 1 - 22:37 riposo notturno<br><br>

<b>VENERDÌ</b><br>
7:15 sveglia - rasatura - ginnastica mattutina: esecuzione tollerabile - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #73921 (ORNSTEIN EMMA): conversazione sulla giornata di lavoro - tragitto in compagnia del soggetto #80085 (DICK ANDREW) - entrata MINISTERO DELLA VERITÀ - 8:30 posizionamento postazione di impiego - inizio mansione: correzione discorso Grande Fratello M383 - numero pagine per annotazioni fornite: 3 - pausa per servizi igienici: incontro con soggetto #80085 (DICK ANDREW): saluto con stretta di mano - termine mansione: correzione discorso Grande Fratello M383 - numero pagine eliminate registrate: 3<br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #91351 (HILL LEON): conversazione riguardante gli interessi procreativi - fine pausa pranzo - inizio mansione: revisione rapporto su tenore di vita N193 - numero pagine per annotazioni fornite: 5 - termine mansione: revisione rapporto su tenore di vita N193 - numero pagine eliminate registrate: 5 - uscita MINISTERO DELLA VERITÀ - tragitto in solitudine - deviazione da percorso abituale<br><br>

19:17 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con #86502 (HANCOCK ALEX): toni amichevoli - 21:27 ritiro nei propri alloggi - manutenzione lavandino - consumo sigarette: quantità: 2 - 22:46 riposo notturno
`
