var s2w3a1 = `<b>LUNEDÌ</b><br>
7:15 sveglia - rasatura - ginnastica mattutina: esercizio svolto in maniera approssimativa - richiamo da parte dell’istruttrice - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW): nessuna informazione - incontro in corridoio con soggetto #73921 (ORNSTEIN EMMA): nessuna informazione - entrata MINISTERO DELLA VERITÀ - 8:29 posizionamento postazione di impiego - inizio mansione: correzione refusi notizie di guerra - termine mansione: correzione refusi notizie di guerra<br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #90672 (HOPPER DANA): nessuna informazione - fine pausa pranzo - inizio mansione: correzione notizie razionamento cioccolato C103 - termine mansione: correzione notizie razionamento cioccolato C103 - uscita MINISTERO DELLA VERITÀ <br><br>

19:18 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #73921 (ORNSTEIN EMMA): evidente preoccupazione - incontro in corridoio con soggetto #80085 (DICK ANDREW): nessuna informazione - 21:33 ritiro nei propri alloggi - pulizia serale - mansioni domestiche - consumo sigarette: quantità: 1 - 22:37 riposo notturno<br><br>

<b>VENERDÌ</b><br>
7:15 sveglia - rasatura - ginnastica mattutina: esecuzione tollerabile - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #73921 (ORNSTEIN EMMA): nessuna informazione - entrata MINISTERO DELLA VERITÀ - 8:30 posizionamento postazione di impiego - inizio mansione: correzione discorso Grande Fratello M383 - pausa per servizi igienici: incontro con soggetto #80085 (DICK ANDREW) - termine mansione: correzione discorso Grande Fratello M383<br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #91351 (HILL LEON): nessuna informazione - fine pausa pranzo - inizio mansione: revisione rapporto su tenore di vita N193 - termine mansione: revisione rapporto su tenore di vita N193 - uscita MINISTERO DELLA VERITÀ - <br><br>

19:17 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con #86502 (HANCOCK ALEX): nessuna informazione - 21:27 ritiro nei propri alloggi - consumo sigarette: quantità: 2 - 22:46 riposo notturno
`

var s2w3a1x = `<b>LUNEDÌ</b><br>
7:15 sveglia - rasatura - ginnastica mattutina: esercizio svolto in maniera approssimativa - richiamo da parte dell’istruttrice - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW): nessuna informazione - incontro in corridoio con soggetto #73921 (ORNSTEIN EMMA): nessuna informazione - entrata MINISTERO DELLA VERITÀ - 8:29 posizionamento postazione di impiego - inizio mansione: correzione refusi notizie di guerra - termine mansione: correzione refusi notizie di guerra<br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #90672 (HOPPER DANA): nessuna informazione - fine pausa pranzo - inizio mansione: correzione notizie razionamento cioccolato C103 - termine mansione: correzione notizie razionamento cioccolato C103 - uscita MINISTERO DELLA VERITÀ <br><br>

19:18 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #73921 (ORNSTEIN EMMA): evidente preoccupazione - incontro in corridoio con soggetto #80085 (DICK ANDREW): nessuna informazione - 21:33 ritiro nei propri alloggi - pulizia serale - mansioni domestiche - consumo sigarette: quantità: 1 - 22:37 riposo notturno<br><br>

<b>VENERDÌ</b><br>
7:15 sveglia - rasatura - ginnastica mattutina: esecuzione tollerabile - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #73921 (ORNSTEIN EMMA): nessuna informazione - entrata MINISTERO DELLA VERITÀ - 8:30 posizionamento postazione di impiego - inizio mansione: correzione discorso Grande Fratello M383 - pausa per servizi igienici - camminata nervosa - ritorno alla postazione di lavoro - termine mansione: correzione discorso Grande Fratello M383<br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #91351 (HILL LEON): nessuna informazione - fine pausa pranzo - inizio mansione: revisione rapporto su tenore di vita N193 - termine mansione: revisione rapporto su tenore di vita N193 - uscita MINISTERO DELLA VERITÀ - <br><br>

19:17 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con #86502 (HANCOCK ALEX): nessuna informazione - 21:27 ritiro nei propri alloggi - consumo sigarette: quantità: 4 - uscita alloggio - camminata nervosa - bussa alla porta di soggetto #80085 (DICK ANDREW) - ritorno in alloggio - 22:46 riposo notturno
`;

var s2w3a2 = `<b>LUNEDÌ</b><br>
7:15 sveglia - rasatura - ginnastica mattutina: esercizio svolto in maniera approssimativa - richiamo da parte dell’istruttrice - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW): toni neutri - incontro in corridoio con soggetto #73921 (ORNSTEIN EMMA): sguardo indifferente - tragitto in compagnia di soggetto #80085 (DICK ANDREW) - entrata MINISTERO DELLA VERITÀ - 8:29 posizionamento postazione di impiego - inizio mansione: correzione refusi notizie di guerra - numero pagine per annotazioni fornite: 4 - RITARDO MACCHINARI DI CONSEGNA DOCUMENTI: non previsto - termine mansione: correzione refusi notizie di guerra - numero pagine eliminate registrate: 4<br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #90672 (HOPPER DANA): sguardi insistenti - fine pausa pranzo - inizio mansione: correzione notizie razionamento cioccolato C103 - numero pagine per annotazioni fornite: 3 - termine mansione: correzione notizie razionamento cioccolato C103 - numero pagine eliminate registrate: 3 - uscita MINISTERO DELLA VERITÀ <br><br>

19:18 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #73921 (ORNSTEIN EMMA): evidente preoccupazione: estratto conversazione [...non preoccuparti abbiamo già aggiustato il lavandino...] - incontro in corridoio con soggetto #80085 (DICK ANDREW): toni preoccupati - 21:33 ritiro nei propri alloggi - pulizia serale - mansioni domestiche - manutenzione lavandino - consumo sigarette: quantità: 1 - 22:37 riposo notturno<br><br>

<b>VENERDÌ</b><br>
7:15 sveglia - rasatura - ginnastica mattutina: esecuzione tollerabile - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #73921 (ORNSTEIN EMMA): conversazione sulla giornata di lavoro - tragitto in compagnia del soggetto #80085 (DICK ANDREW) - entrata MINISTERO DELLA VERITÀ - 8:30 posizionamento postazione di impiego - inizio mansione: correzione discorso Grande Fratello M383 - numero pagine per annotazioni fornite: 3 - pausa per servizi igienici: incontro con soggetto #80085 (DICK ANDREW): saluto con stretta di mano - termine mansione: correzione discorso Grande Fratello M383 - numero pagine eliminate registrate: 3<br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #91351 (HILL LEON): conversazione riguardante gli interessi procreativi - fine pausa pranzo - inizio mansione: revisione rapporto su tenore di vita N193 - numero pagine per annotazioni fornite: 5 - termine mansione: revisione rapporto su tenore di vita N193 - numero pagine eliminate registrate: 5 - uscita MINISTERO DELLA VERITÀ - tragitto in solitudine - deviazione da percorso abituale<br><br>

19:17 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con #86502 (HANCOCK ALEX): toni amichevoli - 21:27 ritiro nei propri alloggi - manutenzione lavandino - consumo sigarette: quantità: 2 - 22:46 riposo notturno
`;

var s2w3a2x = `<b>LUNEDÌ</b><br>
7:15 sveglia - rasatura - ginnastica mattutina: esercizio svolto in maniera approssimativa - richiamo da parte dell’istruttrice - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW): toni neutri - incontro in corridoio con soggetto #73921 (ORNSTEIN EMMA): sguardo indifferente - tragitto in compagnia di soggetto #80085 (DICK ANDREW) - entrata MINISTERO DELLA VERITÀ - 8:29 posizionamento postazione di impiego - inizio mansione: correzione refusi notizie di guerra - numero pagine per annotazioni fornite: 4 - RITARDO MACCHINARI DI CONSEGNA DOCUMENTI: non previsto - termine mansione: correzione refusi notizie di guerra - numero pagine eliminate registrate: 4<br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #90672 (HOPPER DANA): sguardi insistenti - fine pausa pranzo - inizio mansione: correzione notizie razionamento cioccolato C103 - numero pagine per annotazioni fornite: 3 - termine mansione: correzione notizie razionamento cioccolato C103 - numero pagine eliminate registrate: 3 - uscita MINISTERO DELLA VERITÀ <br><br>

19:18 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #73921 (ORNSTEIN EMMA): evidente preoccupazione: estratto conversazione [...non preoccuparti abbiamo già aggiustato il lavandino...] - incontro in corridoio con soggetto #80085 (DICK ANDREW): toni preoccupati - 21:33 ritiro nei propri alloggi - pulizia serale - mansioni domestiche - manutenzione lavandino - consumo sigarette: quantità: 1 - 22:37 riposo notturno<br><br>

<b>VENERDÌ</b><br>
7:15 sveglia - rasatura - ginnastica mattutina: esecuzione tollerabile - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #73921 (ORNSTEIN EMMA): conversazione sulla giornata di lavoro - tragitto in compagnia del soggetto #80085 (DICK ANDREW):toni preoccupati - entrata MINISTERO DELLA VERITÀ - 8:30 posizionamento postazione di impiego - inizio mansione: correzione discorso Grande Fratello M383 - numero pagine per annotazioni fornite: 3 - pausa per servizi igienici - camminata nervosa - arrivo al piano Sezione Intrattenimento e Cinematografia - sosta in corridoio - ritorno alla postazione di lavoro - termine mansione: correzione discorso Grande Fratello M383 - numero pagine eliminate registrate: 3<br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #91351 (HILL LEON): conversazione riguardante gli interessi procreativi - fine pausa pranzo - inizio mansione: revisione rapporto su tenore di vita N193 - numero pagine per annotazioni fornite: 5 - termine mansione: revisione rapporto su tenore di vita N193 - numero pagine eliminate registrate: 5 - uscita MINISTERO DELLA VERITÀ - tragitto in solitudine - deviazione da percorso abituale<br><br>

19:17 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con #86502 (HANCOCK ALEX): toni amichevoli - 21:27 ritiro nei propri alloggi - consumo sigarette: quantità: 4 - uscita alloggio - camminata nervosa - bussa alla porta di soggetto #80085 (DICK ANDREW): toni preoccupati - ritorno in alloggio - manutenzione lavandino - 22:46 riposo notturno
`;

var s2w3a3 = `<b>LUNEDÌ</b><br>
7:15 sveglia - rasatura: usura rasoio 10% - ginnastica mattutina: esercizio svolto in maniera approssimativa - richiamo da parte dell’istruttrice - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW): toni neutri: [...come sta andando?...non c’è altro che posso fare?...] - incontro in corridoio con soggetto #73921 (ORNSTEIN EMMA): sguardo indifferente - tragitto in compagnia di soggetto #80085 (DICK ANDREW) - entrata MINISTERO DELLA VERITÀ - 8:29 posizionamento postazione di impiego - inizio mansione: correzione refusi notizie di guerra - numero pagine per annotazioni fornite: 4 - RITARDO MACCHINARI DI CONSEGNA DOCUMENTI: non previsto - rilevata sudorazione: estratto audio [...ma ha sempre funzionato...] - termine mansione: correzione refusi notizie di guerra - numero pagine eliminate registrate: 4<br><br> 

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #90672 (HOPPER DANA): sguardi insistenti: commenti sull’abbigliamento di #90672 (HOPPER DANA) - fine pausa pranzo - inizio mansione: correzione notizie razionamento cioccolato C103 - numero pagine per annotazioni fornite: 3 - sguardo eccessivamente preoccupato - termine mansione: correzione notizie razionamento cioccolato C103 - numero pagine eliminate registrate: 3 - uscita MINISTERO DELLA VERITÀ<br><br>

19:18 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #73921 (ORNSTEIN EMMA): evidente preoccupazione: estratto conversazione [...non preoccuparti abbiamo già aggiustato il lavandino...] - incontro in corridoio con soggetto #80085 (DICK ANDREW): toni preoccupati: estratto conversazione [...adesso che si fa?...] - 21:33 ritiro nei propri alloggi - pulizia serale - mansioni domestiche - manutenzione lavandino - consumo sigarette: quantità: 1 - 22:37 riposo notturno<br><br>


<b>VENERDÌ</b><br>
7:15 sveglia - rasatura: usura rasoio 50% - ginnastica mattutina: esecuzione tollerabile - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #73921 (ORNSTEIN EMMA): conversazione sulla giornata di lavoro - tragitto in compagnia del soggetto #80085 (DICK ANDREW) - entrata MINISTERO DELLA VERITÀ - 8:30 posizionamento postazione di impiego - inizio mansione: correzione discorso Grande Fratello M383 - numero pagine per annotazioni fornite: 3 - rovista più volte nelle tasche - pausa per servizi igienici: incontro con soggetto #80085 (DICK ANDREW): saluto con stretta di mano - termine mansione: correzione discorso Grande Fratello M383 - numero pagine eliminate registrate: 3<br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #91351 (HILL LEON): conversazione riguardante gli interessi procreativi: estratto conversazione [...forse ho trovata quella giusta...] - fine pausa pranzo - inizio mansione: revisione rapporto su tenore di vita N193 - numero pagine per annotazioni fornite: 5 - termine mansione: revisione rapporto su tenore di vita N193 - numero pagine eliminate registrate: 5 - uscita MINISTERO DELLA VERITÀ - tragitto in solitudine - deviazione da percorso abituale: acquisti a Mercato Nero: 10 sigarette<br><br> 

19:17 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con #86502 (HANCOCK ALEX): toni amichevoli: estratto conversazione [...tra tutti i Condomini Vittoria doveva proprio capitarci lei come istruttrice?...] - 21:27 ritiro nei propri alloggi - manutenzione lavandino - consumo sigarette: quantità: 2 - 22:46 riposo notturno
`;

var s2w3a3x = `<b>LUNEDÌ</b><br>
7:15 sveglia - rasatura: usura rasoio 10% - ginnastica mattutina: esercizio svolto in maniera approssimativa - richiamo da parte dell’istruttrice - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW): toni neutri: [...come sta andando?...non c’è altro che posso fare?...] - incontro in corridoio con soggetto #73921 (ORNSTEIN EMMA): sguardo indifferente - tragitto in compagnia di soggetto #80085 (DICK ANDREW) - entrata MINISTERO DELLA VERITÀ - 8:29 posizionamento postazione di impiego - inizio mansione: correzione refusi notizie di guerra - numero pagine per annotazioni fornite: 4 - RITARDO MACCHINARI DI CONSEGNA DOCUMENTI: non previsto - rilevata sudorazione: estratto audio [...ma ha sempre funzionato...] - termine mansione: correzione refusi notizie di guerra - numero pagine eliminate registrate: 4<br><br> 

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #90672 (HOPPER DANA): sguardi insistenti: commenti sull’abbigliamento di #90672 (HOPPER DANA) - fine pausa pranzo - inizio mansione: correzione notizie razionamento cioccolato C103 - numero pagine per annotazioni fornite: 3 - sguardo eccessivamente preoccupato - termine mansione: correzione notizie razionamento cioccolato C103 - numero pagine eliminate registrate: 3 - uscita MINISTERO DELLA VERITÀ<br><br>

19:18 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #73921 (ORNSTEIN EMMA): evidente preoccupazione: estratto conversazione [...non preoccuparti abbiamo già aggiustato il lavandino...] - incontro in corridoio con soggetto #80085 (DICK ANDREW): toni preoccupati: estratto conversazione [...adesso che si fa?...] - 21:33 ritiro nei propri alloggi - pulizia serale - mansioni domestiche - manutenzione lavandino - consumo sigarette: quantità: 1 - 22:37 riposo notturno<br><br>


<b>VENERDÌ</b><br>
7:15 sveglia - rasatura: usura rasoio 50% - ginnastica mattutina: esecuzione tollerabile - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), #73921 soggetto (ORNSTEIN EMMA): conversazione sulla giornata di lavoro - tragitto in compagnia del soggetto #80085 (DICK ANDREW): toni preoccupati - entrata MINISTERO DELLA VERITÀ - 8:30 posizionamento postazione di impiego - inizio mansione: correzione discorso Grande Fratello M383 - numero pagine per annotazioni fornite: 3 - rovista più volte nelle tasche  - pausa per servizi igienici - camminata nervosa - arrivo al piano Sezione Intrattenimento e Cinematografia - sosta in corridoio in prossimità postazione di soggetto #80085 (DICK ANDREW) - ritorno alla postazione di lavoro - termine mansione: correzione discorso Grande Fratello M383 - numero pagine eliminate registrate: 3<br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #91351 (HILL LEON): conversazione riguardante gli interessi procreativi: estratto conversazione [...forse ho trovata quella giusta...] - fine pausa pranzo - inizio mansione: revisione rapporto su tenore di vita N193 - numero pagine per annotazioni fornite: 5 - termine mansione: revisione rapporto su tenore di vita N193 - numero pagine eliminate registrate: 5 - uscita MINISTERO DELLA VERITÀ - tragitto in solitudine - deviazione da percorso abituale: acquisti a Mercato Nero: 10 sigarette<br><br> 

19:17 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con #86502 (HANCOCK ALEX): toni amichevoli: estratto conversazione [...tra tutti i Condomini Vittoria doveva proprio capitarci lei come istruttrice?...] - 21:27 ritiro nei propri alloggi - consumo sigarette: quantità: 4 - uscita alloggio - camminata nervosa - bussa alla porta di soggetto #80085 (DICK ANDREW): toni preoccupati: estratto conversazione [...è successo qualcosa?...problemi al bar?...] - ritorno in alloggio - manutenzione lavandino - 22:46 riposo notturno
`;

var s2b3 = `Come richiesto ho cercato di approfondire il discorso sel soggetto #87013 (MINSON PETER) sull’inceneritore. Ho aspettato la domenica e ho usato il giorno festivo come scusa per farlo ubriacare con del gin Vittoria che ho richiesto in mensa.<br><br> Dai suoi racconti non sembra aver sfruttato il malfunzionamento per fini psicocriminali, ma è comunque diventato in qualche modo sospetto; ha alluso al fatto che la razione di cioccolato per ogni cittadino potrebbe non essere aumentata a 18 grammi ma bensì, se non ricorda male (dice), sia diminuita e potrebbe persino avere le prove se decidesse di sottrarle al Partito con il metodo citato in precedenza.
`;