var s2w4a3 = `<b>MERCOLEDÌ</b><br>
7:15 sveglia - rasatura: usuro rasoio: 80% - ginnastica mattutina: esecuzione tollerabile - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW): toni neutri: estratto conversazione [...sicuro non ti serva una mano al bar?...] - tragitto in compagnia di soggetto #80085 (DICK ANDREW): rilevate smorfie di disappunto - entrata MINISTERO DELLA VERITÀ - scambio di saluti con #90672 (HOPPER DANA): sguardi affetuosi - 8:30 posizionamento postazione di impiego - inizio mansione: revisione dati forniti da MINISTERO DELL’ABBONDANZA - numero pagine per annotazioni fornite: 5 - termine mansione: revisione dati forniti da MINISTERO DELL’ABBONDANZA - numero pagine per annotazioni eliminate registrate: 5<br><br>

12:00 pausa pranzo mensa MINISTERO DELLA VERITÀ: colloquio con #91351 (HILL LEON), #90672 (HOPPER DANA): toni amichevoli: estratto conversazione [...ragazzi potremmo vederci al di fuori del lavoro ogni tanto...] - fine pausa pranzo - inizio mansione: correzione refusi di guerra malriportati - numero pagine per annotazioni fornite: 3 - termine mansione: correzione refusi di guerra malriportati - pagine per annotazioni eliminate registrate: 3 - uscita MINISTERO DELLA VERITÀ - tragitto in solitudine<br><br>

19:17 entrata CONDOMINIO VITTORIA 111 - pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #73921 (ORNSTEIN EMMA), #86502 (HANCOCK ALEX), #75293 (GRANT FINN): discussione riguardo alle presenza all’attività domenicale: estratto conversazione [...non lo so ancora, dipende da quanto sarò stanco...] - 21:20 ritiro nei propri alloggi - consumo sigarette: quantità: 3 - 22:27 riposo notturno<br><br>

<b>DOMENICA</b><br>
8:00 sveglia - ginnastica mattutina: esecuzione accettabile - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #73921 (ORNSTEIN EMMA): giustificazione per mancata partecipazione a gita domenicale: estratto conversazione [...è stata una settimana dura...preferisco riposare...] - ritorno in alloggio - manutenzione lavandino: interruzione da parte di #73921 (ORNSTEIN EMMA): bussa alla porta: giustificazione affrettata: estratto conversazione [...ma quale rumore?...sto sbrigando delle faccende, lasciami stare...] - visione teleschermo: notiziario H203<br><br>

12:03 pausa pranzo mensa CONDOMINIO VITTORIA 111: colloquio con #86502 (HANCOCK ALEX): toni amichevoli: estratto conversazione [...stamattina hai partecipato alla gita?...] - ritiro in alloggio - consumo sigarette: quantità: 5 - rovista sotto lavandino - uscita alloggio - camminata nervosa - bussa a porta soggetto #80085 (DICK ANDREW): nessuna risposta - ritorno in alloggio - 15:05 uscita CONDOMINIO VITTORIA 111 - 15:52 arrivo BAR DELL’OLMO: conversazione con prolet all’entrata: toni minacciosi: estratto conversazione [...al diavolo la parola segreta...devo parlare con Dick, fammi entrare!...] - entrata negata - sosta davanti BAR DELL’OLMO - 17:43 entrata CONDOMINIO VITTORIA 111 - incontro in corridoio con soggetto #73921 (ORNSTEIN EMMA): scambio di sguardi intimidatori - ritiro in alloggio<br><br>

19:00 pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW): toni di scuse: parole indecifrabili - 21:14 ritiro nei propri alloggi - consumo sigarette: quantità: 2 - pulizia serale - 22:49 riposo notturno

`
