var s3w2a2 = `<b>GIOVEDÌ</b><br>
7:00 sveglia - coordinamento ginnastica mattutina per gli impiegati d’ufficio - pulizia mattutina - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #87013 (MINSON PETER): evidente interesse: estratto comunicazione [...cosa dovevate fare martedì sera di così importante?...] - posizionamento in UFFICIO CONDOMINIO VITTORIA 111 - 9:30 inizio mansione: organizzazione gita domenicale - termine mansione: organizzazione gita domenicale - inizio mansione: redazione lista presenze a gita domenicale - termine mansione: redazione lista presenze a gita domenicale<br><br>

12:00 pausa pranzo mensa CONDOMINIO VITTORIA 111: colloquio con #86502 (HANCOCK ALEX): rimprovero: estratto conversazione [...dovresti contribuire anche te alle pulizie ogni tanto...] - fine pausa pranzo - 15:00 inizio mansione: coordinamento pulizia e manutenzione CONDOMINIO VITTORIA 111 - colloquio con #77320 (KOR ELEANOR): toni amichevoli: estratto conversazione [...non vedo l’ora di partecipare al discorso di questa domenica...] - termine mansione: coordinamento pulizia e manutenzione CONDOMINIO VITTORIA 111<br><br>

19:10 pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con #75293 (GRANT FINN): toni amichevoli: estratto conversazione [...ah anche tu hai servito il Partito come mio figlio...] - 21:16 ritiro nei propri alloggi - visione trasmissione teleschermo: notiziario K230 - interruzione per fetore percepito - arrivo a porta soggetto #87013 (MINSON PETER): richiamo infastidito: estratto conversazione [...ti pare il caso di fumare quelle schifezze a quest’ora?...] - ritorno in alloggio - 22:20 riposo notturno<br><br>

<b>DOMENICA</b><br>
7:45 sveglia - coordinamento ginnastica mattutina domenicale: richiamo #86502 (HANCOCK ALEX) - pulizia mattutina - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #87013 (MINSON PETER): toni motivazionali: estratto conversazione [...Minson...questo evento è imperdibile...] - inizio coordinamento attività facoltativa: discorso partito interno Hyde Park - 9:15 partenza da CONDOMINIO VITTORIA 111 - 10:02 arrivo ad Hyde Park - ascolto affascinato del discorso - termine attività facoltativa: discorso partito interno Hyde Park<br><br>

12:00 entrata CONDOMINIO VITTORIA 111 - pausa pranzo mensa CONDOMINIO VITTORIA 111: colloquio con #75293 (GRANT FINN): toni amichevoli: mostra ammirazione: estratto conversazione [...avrei voluto ci fose stato mio figlio...l’avrebbe adorata...] - 15:30 accesso alloggio - visione trasmissione teleschermo: discorso Grande Fratello C112 - uscita alloggio - arrivo a porta del soggetto #87013 (MINSON PETER): bussa alla porta e offre aiuto: toni amichevoli: estratto conversazione [...sono sempre disponibile a darvi una mano...cari...] - aiuto respinto - ritorno in alloggio - visione trasmissione teleschermo: notiziario K231<br><br>

19:00 pasto serale mensa CONDOMINIO VITTORIA 111 - 21:10 ritiro nei propri alloggi - visione trasmissione teleschermo: discorso grande fratello C112, notiziario K235 - accostamento alla parete confinante con soggetto #87013 (MINSON PETER) - 22:12 riposo notturno
`
