var s3w3a2 = `<b>LUNEDÌ</b><br>
7:00 sveglia - coordinamento ginnastica mattutina per gli impiegati d’ufficio: richiamo soggetto #87013 (MINSON PETER), #86502 (HANCOCK ALEX): tono scocciato: estratto audio [...Minson, Hancock...toccate quelle punte!...] - pulizia mattutina - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con #75293 (GRANT FINN): toni amichevoli: estratto conversazione [...è così bello parlare con te Finn...] - incontro in corridoio con soggetto #87013 (MINSON PETER): sguardo accusatorio - inizio mansione: coordinamento raccolta viveri settimanali condominio - colloquio con corriere #72842 (GREEN STEPHEN): toni neutri: estratto conversazione [...preferirei puntualità la prossima volta...] - termine mansione: coordinamento raccolta viveri settimanali condominio - posizionamento in UFFICIO CONDOMINIO VITTORIA 111 - 10:00 inizio mansione: organizzazione pasti settimanali condominio - cucine CONDOMINIO VITTORIA 111: colloquio con cuoca #709011 (ROGAN LANA): richiamo: conversazione riguardo alle lamentele dei condomini sul cibo a mensa - redazione lista pasti settimanali - termine mansione: organizzazione pasti settimanali condominio<br><br>

12:00 pausa pranzo mensa CONDOMINIO VITTORIA 111 - fine pausa pranzo - inizio mansione: organizzazione pulizia e manutenzione settimanale condominio - termine mansione: organizzazione pulizia e manutenzione settimanale condominio<br><br>

19:24 pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #87013 (MINSON PETER): offerta insistente di aiuto: estratto conversazione [...oggi ti aiuto io per la manutenzione delle tubature...] - 21:22 ritiro nei propri alloggi - visione trasmissione teleschermo: discorso Grande Fratello C113, notiziario K236 - accostamento alla parete confinante con soggetto #87013 (MINSON PETER) - 22:27 riposo notturno<br><br>

<b>VENERDÌ</b><br>
7:00 sveglia - coordinamento ginnastica mattutina per gli impiegati d’ufficio - pulizia mattutina - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #87013 (MINSON PETER): toni neutri: conversazione sulla giornata di lavoro - inizio mansione: coordinamento pulizia condominio - termine mansione: coordinamento pulizia condominio<br><br>

12:00 pausa pranzo mensa CONDOMINIO VITTORIA 111: colloquio con #77320 (KOR ELEANOR): toni amichevoli: estratto conversazione [...tu cosa ne pensi di Finn Grant?...] - fine pausa pranzo - posizionamento in UFFICIO CONDOMINIO VITTORIA 111 - inizio mansione: organizzazione assemblea condominiale - registro presenze condomini - pausa dal lavoro - sosta su porta soggetto #87013 (MINSON PETER): tentata intrusione: non riuscita - termine mansione: organizzazione assemblea condominiale<br><br>

19:20 pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW): discorso riguardante il soggetto #87013 (MINSON PETER): estratto conversazione [...tu che gli sei molto vicino, non pensi che Peter sia un po’ sospetto?...magari è uno psicocriminale...] - 21:03 ritiro nei propri alloggi - visione trasmissione teleschermo: discorso grande fratello C032, notiziario K240 - accostamento alla parete confinante con soggetto #87013 (MINSON PETER) - 22:10 riposo notturno
`
