var s3w4a2 = `<b>MERCOLEDÌ</b><br>
7:00 sveglia - coordinamento ginnastica mattutina per gli impiegati d’ufficio - pulizia mattutina - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #75293 (GRANT FINN): evidente interesse: estratto conversazione [...sembra che tu sia l’unico di cui io mi possa fidare qua dentro...cosa ne farebbe di me il Partito se scoprisse che ci sono degli psicocriminali nel condominio?...devo trovare le prove...] - posizionamento in UFFICIO CONDOMINIO VITTORIA 111 - 10:00 inizio mansione: coordinamento pulizia e manutenzione condominio - termine mansione: coordinamento pulizia e manutenzione condominio<br><br>

12:00 pausa pranzo mensa CONDOMINIO VITTORIA 111: colloquio con #86502 (HANCOCK ALEX), #77320 (KOR ELEANOR): conversazione riguardante gli altri condomini: estratto conversazione [...pensavo di potermi fidare, ma ho bisogno di sapere dove siete finiti domenica scorsa...siete spariti per un’ora...] - fine pausa pranzo - 15:00 inizio mansione: controllo periodico impianti appartamenti CONDOMINIO VITTORIA 111 - termine mansione: controllo periodico impianti appartamenti CONDOMINIO VITTORIA 111<br><br>

19:10 pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #87013 (MINSON PETER), #86502 (HANCOCK ALEX), #75293 (GRANT FINN): discussione riguardo alle presenza all’attività domenicale: estratto conversazione [...vi voglio tutti lì, vedete di esserci!...] - 21:10 ritiro nei propri alloggi - visione trasmissione teleschermo: discorso grande fratello C089, notiziario K245 - 22:15 riposo notturno<br><br>

<b>DOMENICA<br>
7:45 sveglia - coordinamento ginnastica mattutina domenicale: richiamo #86502 (HANCOCK ALEX): toni minacciosi: estratto conversazione [...non è possibile Hancock...non ti impegni per nulla!...] - pulizia mattutina - pasto mattutino mensa CONDOMINIO VITTORIA 111: colloquio con soggetto #80085 (DICK ANDREW), soggetto #87013 (MINSON PETER): toni evidentemente preoccupati: estratto conversazione [...non capisco davvero cosa possiate avere di meglio da fare piuttosto che partecipare a queste magnifiche manifestazioni del Partito Interno...] - ritorno in alloggio per preparazione ad attività - rumori percepiti da stanza soggetto #87013 (MINSON PETER): bussa e chiede spiegazioni: estratto conversazione [...mi spieghi cos’era quel rumore che ho sentito?...di cosa ti stai occupando?...] - inizio coordinamento attività facoltativa: discorso partito interno e impiccagione prigionieri di guerra a Trafalgar Square - 9:00 partenza da CONDOMINIO VITTORIA 111 - 10:05 arrivo ad Trafalgar Square - ascolto affascinato del discorso - urla di incitamento - termine attività facoltativa: discorso partito interno e impiccagione prigionieri di guerra a Trafalgar Square<br><br>

13:00 entrata CONDOMINIO VITTORIA 111 - pausa pranzo mensa CONDOMINIO VITTORIA 111: colloquio con #75293 (GRANT FINN): conversazione riguardo alla sua indagine sui condomini: estratto conversazione [...credo la situazione sia peggiore di quanto pensassi...Hancock e Eleanor che spariscono insieme e Minson mi nasconde sicuramente qualcosa!...devo capire cosa...] - 14:32 accesso alloggio - visione trasmissione teleschermo: discorso Grande Fratello C112 - rumori in corridoio - uscita da alloggio - arrivo a porta soggetto #87013 (MINSON PETER): bussa e prova ad entrare: accesso riuscito - rovista sotto al lavandino: estratto audio [...avevo ragione!...] - uscita da stanza soggetto #87013 (MINSON PETER) - camminata nervosa - ritorno in alloggio - visione trasmissione teleschermo: notiziario K231<br><br>

19:00 pasto serale mensa CONDOMINIO VITTORIA 111: colloquio con #86502 (HANCOCK ALEX), #77320 (KOR ELEANOR): toni neutri [...se dovessi scoprire qualcosa...non avete idea...] - 21:23 ritiro nei propri alloggi - visione trasmissione teleschermo: discorso grande fratello C097, notiziario K250 - 22:05 bussa a porta di soggetto #80085 (DICK ANDREW): accesso alloggio soggetto #80085 (DICK ANDREW): toni minacciosi: estratto conversazione [...so tutto...tu e Minson...che vi incontrate di nascosto con la scusa delle tubature malfunzionanti...se non mi spieghi subito vi segnalerò entrambi per psicoreato!...] - ritorno in alloggio - 22:35 riposo notturno

`
